apiVersion: apps/v1
kind: Deployment
metadata:
 name: maven-deploy
 labels:
   app: mavenapp
spec:
 replicas: 3
 selector:
   matchLabels:
     app: mavenapp
 template:
   metadata:
     labels:
       app: mavenapp
   spec:
     containers:
     - name: mavenapp
       image: sahiljangra/mavenapp:latest
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
    - port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30009
